name: My Github Actions Workflow
on: [push]

jobs:
  testing_github:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello, github actions"
      - name: Display repo                                        
        run: echo "this workflow is running in ${{ github.repository }}"

        